### ISSUE TITLE
roadmap for v1.5 (assignment changes)

### ISSUE THREAD

**Issue by raphaelquast** [raphaelquast/beatstep#29]
- [x] exchange pad-rows in "track control" layer
- make the top row "mute/solo" tracks and the bottom row "arm" tracks (this fits better to ableton's UI)

- [x] switch light indicators if "shift-pressed" 
- again the bottom row should indicate the "arm" state and the top-row the "track-type" 

- [ ] change encoder assignments in "clip-launch" layer
- the encoders should behave similar to the "track-control" layer (to easily change volume, pan and sends of each track)

- [ ] overlay design
